volumes:
  api-node-modules:
    name: ${PROJECT_TAG}-api-node-modules
  mailer-node-modules:
    name: ${PROJECT_TAG}-mailer-node-modules
  panel-react-node-modules:
    name: ${PROJECT_TAG}-panel-react-node-modules
  panel-vue-node-modules:
    name: ${PROJECT_TAG}-panel-vue-node-modules

services:
  grafana:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  nginx:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/nginx/html:/usr/share/nginx/html
      - ./infrastructure/nginx/ssl:/usr/share/nginx/ssl
      - ./infrastructure/nginx/templates:/etc/nginx/templates

  rabbitmq:
    restart: no
    ports:
      - 15672:15672
    env_file:
      - .env
    volumes:
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  postgres:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
  postgres-exporter:
    restart: no
  adminer:
    image: adminer:standalone
    container_name: ${PROJECT_TAG}-adminer
    restart: no
    networks:
      - main
    ports:
      - 8080:8080
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.200'
          memory: 256M
        reservations:
          cpus: '0.050'
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    build:
      target: development
    restart: no
    ports:
      - 8001:8001
    env_file:
      - .env
    volumes:
      - ./infrastructure/redis/redis-stack.conf:/redis-stack.conf
  redis-exporter:
    restart: no

  api:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./apps/backend/api:/usr/src/app/apps/backend/api
      - ./shared:/usr/src/app/shared
      - api-node-modules:/usr/src/app/apps/backend/api/node_modules
  mailer:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./apps/backend/mailer:/usr/src/app/apps/backend/mailer
      - ./shared:/usr/src/app/shared
      - mailer-node-modules:/usr/src/app/apps/backend/mailer/node_modules
  panel-react:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./apps/frontend/panel-react:/usr/src/app/apps/frontend/panel-react
      - ./shared:/usr/src/app/shared
      - panel-react-node-modules:/usr/src/app/apps/frontend/panel-react/node_modules
    deploy:
      resources:
        limits:
          cpus: '4.000'
          memory: 4096M
        reservations:
          cpus: '1.000'
          memory: 1024M
  panel-vue:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./apps/frontend/panel-vue:/usr/src/app/apps/frontend/panel-vue
      - ./shared:/usr/src/app/shared
      - panel-vue-node-modules:/usr/src/app/apps/frontend/panel-vue/node_modules
    deploy:
      resources:
        limits:
          cpus: '4.000'
          memory: 4096M
        reservations:
          cpus: '1.000'
          memory: 1024M
