version: "3.8"

services:

  nginx:
    build:
      target: development
    volumes:
      - "./nginx:/home/${PROJECT_TAG}/nginx"

  rabbitmq:
    build:
      target: development
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  redis:
    build:
      target: development
    ports:
      - ${REDIS_INSIGHT_PORT}:8001
    volumes:
      - "./redis:/home/${PROJECT_TAG}/redis"

  nest_core:
    build:
      target: development
    volumes:
      - "./nest_core:/home/${PROJECT_TAG}/nest_core"

  nest_mailer:
    build:
      target: development
    volumes:
      - "./nest_mailer:/home/${PROJECT_TAG}/nest_mailer"

  next:
    build:
      target: development
    volumes:
      - "./next:/home/${PROJECT_TAG}/next"

  nuxt:
    build:
      target: development
    volumes:
      - "./nuxt:/home/${PROJECT_TAG}/nuxt"

  adminer:
    build:
      context: ./adminer
    container_name: ${PROJECT_TAG}_adminer
    restart: always
    env_file:
      - .env
    networks:
      - main
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}