version: "3.8"

services:

  nginx:
    build:
      target: development
    volumes:
      - ./nginx:/home/nginx

  rabbitmq:
    build:
      target: development
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  redis:
    build:
      target: development
    ports:
      - ${REDIS_INSIGHT_PORT}:8001
    volumes:
      - ./redis:/home/redis

  nest_core:
    build:
      target: development
    volumes:
      - ./nest_core:/home/node

  nest_mailer:
    build:
      target: development
    volumes:
      - ./nest_mailer:/home/node

  next:
    build:
      target: development
    volumes:
      - ./next:/home/node

  nuxt:
    build:
      target: development
    volumes:
      - ./nuxt:/home/bun

  adminer:
    build:
      context: ./adminer
    container_name: ${PROJECT_TAG}_adminer
    restart: always
    env_file:
      - .env
    networks:
      - main
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}