volumes:
  api-node-modules:
    name: ${PROJECT_TAG}-api-node-modules
  mailer-node-modules:
    name: ${PROJECT_TAG}-mailer-node-modules
  panel-react-node-modules:
    name: ${PROJECT_TAG}-panel-react-node-modules
  panel-vue-node-modules:
    name: ${PROJECT_TAG}-panel-vue-node-modules

services:
  grafana:
    env_file:
      - .env
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    env_file:
      - .env
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  nginx:
    env_file:
      - .env
    volumes:
      - ./infrastructure/nginx/html:/usr/share/nginx/html
      - ./infrastructure/nginx/ssl:/usr/share/nginx/ssl
      - ./infrastructure/nginx/templates:/etc/nginx/templates

  rabbitmq:
    ports:
      - 15672:15672
    env_file:
      - .env
    volumes:
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  postgres:
    env_file:
      - .env
    volumes:
      - ./infrastructure/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
  adminer:
    image: adminer:standalone
    container_name: ${PROJECT_TAG}-adminer
    restart: always
    networks:
      - main
    ports:
      - 8080:8080
    env_file:
      - .env

  redis:
    build:
      target: development
    ports:
      - 8001:8001
    env_file:
      - .env
    volumes:
      - ./infrastructure/redis/redis-stack.conf:/redis-stack.conf

  api:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./apps/backend/api:/usr/src/app/apps/backend/api
      - ./shared:/usr/src/app/shared
      - api-node-modules:/usr/src/app/apps/backend/api/node_modules
  mailer:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./apps/backend/mailer:/usr/src/app/apps/backend/mailer
      - ./shared:/usr/src/app/shared
      - mailer-node-modules:/usr/src/app/apps/backend/mailer/node_modules
  panel-react:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./apps/frontend/panel-react:/usr/src/app/apps/frontend/panel-react
      - ./shared:/usr/src/app/shared
      - panel-react-node-modules:/usr/src/app/apps/frontend/panel-react/node_modules
  panel-vue:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./apps/frontend/panel-vue:/usr/src/app/apps/frontend/panel-vue
      - ./shared:/usr/src/app/shared
      - panel-vue-node-modules:/usr/src/app/apps/frontend/panel-vue/node_modules
