volumes:
  nest_core_node_modules:
    name: ${PROJECT_TAG}_nest_core_node_modules
  nest_mailer_node_modules:
    name: ${PROJECT_TAG}_nest_mailer_node_modules
  next_node_modules:
    name: ${PROJECT_TAG}_next_node_modules
  nuxt_node_modules:
    name: ${PROJECT_TAG}_nuxt_node_modules

services:
  nginx:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./nginx/html:/home/nginx/html
      - ./nginx/ssl:/home/nginx/ssl
      - ./nginx/templates:/home/nginx/templates

  rabbitmq:
    build:
      target: development
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    env_file:
      - .env
    volumes:
      - ./rabbitmq/conf.d:/home/rabbitmq/conf.d

  postgres:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./postgres/postgresql.conf:/home/postgres/postgresql.conf

  adminer:
    image: adminer:standalone
    container_name: ${PROJECT_TAG}_adminer
    restart: always
    networks:
      - main
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    env_file:
      - .env

  redis:
    build:
      target: development
    ports:
      - ${REDIS_INSIGHT_PORT}:8001
    env_file:
      - .env
    volumes:
      - ./redis/redis-stack.conf:/redis-stack.conf

  nest_core:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./nest_core:/home/node
      - ./shared:/home/node/src/shared
      - nest_core_node_modules:/home/node/node_modules

  nest_mailer:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./nest_mailer:/home/node
      - ./shared:/home/node/src/shared
      - nest_mailer_node_modules:/home/node/node_modules

  next:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./next:/home/node
      - ./shared:/home/shared
      - next_node_modules:/home/node/node_modules

  nuxt:
    build:
      target: development
    env_file:
      - .env
    volumes:
      - ./nuxt:/home/bun
      - ./shared:/home/shared
      - nuxt_node_modules:/home/bun/node_modules
