version: "3.8"

services:

  adminer:
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  redis:
    build:
      target: development
    ports:
      - ${REDIS_INSIGHT_PORT}:8001

  nest_core:
    build:
      target: development
    volumes:
      - "./nest_core:/home/${PROJECT_TAG}/nest_core"

  rabbitmq:
    build:
      target: development
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  next:
    build:
      target: development
    volumes:
      - "./next:/home/${PROJECT_TAG}/next"

  nginx:
    build:
      target: development
    volumes:
      - "./nginx:/home/${PROJECT_TAG}/nginx"