version: "3.8"

services:

  adminer:
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  redis:
    build:
      target: development
    ports:
      - ${REDIS_INSIGHT_PORT}:8001

  nest:
    build:
      target: development
    volumes:
      - "./nest:/home/${PROJECT_TAG}/nest"

  next:
    build:
      target: development
    volumes:
      - "./next:/home/${PROJECT_TAG}/next"

  nginx:
    build:
      target: development
    volumes:
      - "./nginx:/home/${PROJECT_TAG}/nginx"