version: "3.8"

volumes:
  rabbitmq_data:
    name: ${PROJECT_TAG}_rabbitmq_data
  postgres_data:
    name: ${PROJECT_TAG}_postgres_data
  redis_data:
    name: ${PROJECT_TAG}_redis_data
  nest_core_node_modules:
    name: ${PROJECT_TAG}_nest_core_node_modules
  nest_mailer_node_modules:
    name: ${PROJECT_TAG}_nest_mailer_node_modules
  next_node_modules:
    name: ${PROJECT_TAG}_next_node_modules
  nuxt_node_modules:
    name: ${PROJECT_TAG}_nuxt_node_modules

networks:
  main:
    name: ${PROJECT_TAG}_main

services:

  nginx:
    build:
      context: ./nginx
      args:
        - PROJECT_TAG=${PROJECT_TAG}
    container_name: ${PROJECT_TAG}_nginx
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${NGINX_PORT}
      - ${NGINX_SSL_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: ${PROJECT_TAG}_rabbitmq
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${RABBITMQ_PORT}
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  postgres:
    build:
      context: ./postgres
    container_name: ${PROJECT_TAG}_postgres
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  adminer:
    build:
      context: ./adminer
    container_name: ${PROJECT_TAG}_adminer
    restart: always
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - postgres

  redis:
    build:
      context: ./redis
    container_name: ${PROJECT_TAG}_redis
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${REDIS_PORT}
    volumes:
      - "redis_data:/data"

  nest_mailer:
    build:
      context: ./nest_mailer
      args:
        - PROJECT_TAG=${PROJECT_TAG}
    container_name: ${PROJECT_TAG}_nest_mailer
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${NEST_MAILER_PORT}
    depends_on:
      - rabbitmq
    volumes:
      - "nest_mailer_node_modules:/home/${PROJECT_TAG}/nest_mailer/node_modules"

  nest_core:
    build:
      context: ./nest_core
      args:
        - PROJECT_TAG=${PROJECT_TAG}
    container_name: ${PROJECT_TAG}_nest_core
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${NEST_CORE_PORT}
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - "nest_core_node_modules:/home/${PROJECT_TAG}/nest_core/node_modules"

  next:
    build:
      context: ./next
      args:
        - PROJECT_TAG=${PROJECT_TAG}
    container_name: ${PROJECT_TAG}_next
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${NEXT_PORT}
    volumes:
      - "next_node_modules:/home/${PROJECT_TAG}/next/node_modules"

  nuxt:
    build:
      context: ./nuxt
      args:
        - PROJECT_TAG=${PROJECT_TAG}
    container_name: ${PROJECT_TAG}_nuxt
    restart: always
    env_file:
      - .env
    networks:
      - main
    expose:
      - ${NUXT_PORT}
    volumes:
      - "nuxt_node_modules:/home/${PROJECT_TAG}/nuxt/node_modules"