version: "3.8"

networks:
  main:
    name: ${PROJECT_TAG}_main

volumes:
  rabbitmq_data:
    name: ${PROJECT_TAG}_rabbitmq_data
  postgres_data:
    name: ${PROJECT_TAG}_postgres_data
  redis_data:
    name: ${PROJECT_TAG}_redis_data

services:

  nginx:
    build:
      context: ./nginx
    container_name: ${PROJECT_TAG}_nginx
    restart: always
    networks:
      - main
    expose:
      - ${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: ${PROJECT_TAG}_rabbitmq
    restart: always
    networks:
      - main
    expose:
      - ${RABBITMQ_PORT}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    build:
      context: ./postgres
    container_name: ${PROJECT_TAG}_postgres
    restart: always
    networks:
      - main
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    build:
      context: ./redis
    container_name: ${PROJECT_TAG}_redis
    restart: always
    networks:
      - main
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/data

  nest_core:
    build:
      context: ./nest_core
    container_name: ${PROJECT_TAG}_nest_core
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - main
    expose:
      - ${NEST_CORE_PORT}

  nest_mailer:
    build:
      context: ./nest_mailer
    container_name: ${PROJECT_TAG}_nest_mailer
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - main
    expose:
      - ${NEST_MAILER_PORT}

  next:
    build:
      context: ./next
    container_name: ${PROJECT_TAG}_next
    restart: always
    networks:
      - main
    expose:
      - ${NEXT_PORT}
    environment:
      - HOSTNAME=${NEXT_HOST}
      - PORT=${NEXT_PORT}

  nuxt:
    build:
      context: ./nuxt
    container_name: ${PROJECT_TAG}_nuxt
    restart: always
    networks:
      - main
    expose:
      - ${NUXT_PORT}
    environment:
      - HOSTNAME=${NUXT_HOST}
      - PORT=${NUXT_PORT}
