services:
  nginx:
    build:
      target: production
    environment:
      - NGINX_HOST
      - NGINX_PORT
      - NGINX_SSL_PORT
      - NGINX_ENVSUBST_TEMPLATE_DIR
      - NEXT_HOST
      - NEXT_PORT
      - NUXT_HOST
      - NUXT_PORT
      - NEST_CORE_HOST
      - NEST_CORE_PORT

  rabbitmq:
    build:
      target: production
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  postgres:
    build:
      target: production
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  redis:
    build:
      target: production
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_ARGS
      - REDIS_INSIGHT_PORT

  nest_core:
    build:
      target: production
    environment:
      - NEST_CORE_HOST
      - NEST_CORE_PORT
      - NGINX_HOST
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_MAIL_QUEUE
      - MAIL_REGISTRATION
      - MAIL_FORGOT_PASSWORD
      - MAIL_CHANGE_EMAIL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USER
      - REDIS_PASSWORD
      - REDIS_DB
      - ACCESS_TOKEN_LIFETIME
      - ACCESS_TOKEN_SECRET_KEY
      - REFRESH_TOKEN_LIFETIME
      - REFRESH_TOKEN_SECRET_KEY

  nest_mailer:
    build:
      target: production
    environment:
      - PROJECT_TAG
      - NEST_MAILER_HOST
      - NEST_MAILER_PORT
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_MAIL_QUEUE
      - MAIL_REGISTRATION
      - MAIL_FORGOT_PASSWORD
      - MAIL_CHANGE_EMAIL
      - NEST_MAILER_MAIL_HOST
      - NEST_MAILER_MAIL_PORT
      - NEST_MAILER_MAIL_USER
      - NEST_MAILER_MAIL_PASSWORD

  next:
    build:
      target: production
      args:
        - NGINX_HOST
        - NEXT_HOST_PREFIX
        - NEST_CORE_HOST
        - NEST_CORE_PORT
        - GOOGLE_CLIENT_ID

  nuxt:
    build:
      target: production
      args:
        - NGINX_HOST
        - NUXT_HOST_PREFIX
        - NEST_CORE_HOST
        - NEST_CORE_PORT
        - GOOGLE_CLIENT_ID
