services:
  grafana:
    environment:
      - TZ
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD__FILE
      - GF_USERS_ALLOW_SIGN_UP
      - GF_INSTALL_PLUGINS
  prometheus:
    environment:
      - TZ

  nginx:
    environment:
      - TZ
      - NGINX_HOST
      - NGINX_PORT
      - NGINX_SSL_PORT
      - API_HOST
      - API_PORT
      - API_URL
      - PANEL_REACT_HOST
      - PANEL_REACT_PORT
      - PANEL_REACT_URL
      - PANEL_VUE_HOST
      - PANEL_VUE_PORT
      - PANEL_VUE_URL

  rabbitmq:
    environment:
      - TZ
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_PROMETHEUS_RETENTION_POLICY

  postgres:
    environment:
      - TZ
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  redis:
    build:
      target: production
    environment:
      - TZ
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_ARGS

  api:
    build:
      target: production
    environment:
      - TZ
      - API_HOST
      - API_PORT
      - API_ACCESS_TOKEN_LIFETIME
      - API_REFRESH_TOKEN_LIFETIME
      - NGINX_HOST
      - PANEL_REACT_URL
      - PANEL_VUE_URL
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_MAIL_QUEUE
      - MAILER_CMD_REGISTRATION
      - MAILER_CMD_FORGOT_PASSWORD
      - MAILER_CMD_CHANGE_EMAIL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USER
      - REDIS_PASSWORD
      - REDIS_DB
  mailer:
    build:
      target: production
    environment:
      - TZ
      - MAILER_HOST
      - MAILER_PORT
      - MAILER_SMTP_HOST
      - MAILER_SMTP_PORT
      - MAILER_SMTP_USER
      - MAILER_CMD_REGISTRATION
      - MAILER_CMD_FORGOT_PASSWORD
      - MAILER_CMD_CHANGE_EMAIL
      - PROJECT_TAG
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_MAIL_QUEUE
  panel-react:
    build:
      target: production
      args:
        - TZ
        - PANEL_REACT_URL
        - API_HOST
        - API_PORT
        - API_URL
        - GOOGLE_CLIENT_ID
  panel-vue:
    build:
      target: production
      args:
        - TZ
        - PANEL_VUE_URL
        - API_HOST
        - API_PORT
        - API_URL
        - GOOGLE_CLIENT_ID
