version: "3.8"

services:

  redis:
    build:
      target: production

  nest:
    build:
      target: production

  next:
    build:
      target: production

  nginx:
    build:
      target: production