version: "3.8"

services:

  redis:
    build:
      target: production

  nest_core:
    build:
      target: production

  rabbitmq:
    build:
      target: production

  next:
    build:
      target: production

  nginx:
    build:
      target: production