services:
  nginx:
    build:
      target: production
    environment:
      - NGINX_HOST
      - NGINX_PORT
      - NGINX_SSL_PORT
      - API_HOST
      - API_PORT
      - API_URL
      - PANEL_REACT_HOST
      - PANEL_REACT_PORT
      - PANEL_REACT_URL
      - PANEL_VUE_HOST
      - PANEL_VUE_PORT
      - PANEL_VUE_URL

  rabbitmq:
    build:
      target: production
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  postgres:
    build:
      target: production
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  redis:
    build:
      target: production
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_ARGS
      - REDIS_INSIGHT_PORT

  mailer:
    build:
      target: production
    environment:
      - MAILER_HOST
      - MAILER_PORT
      - MAILER_SMTP_HOST
      - MAILER_SMTP_PORT
      - MAILER_SMTP_USER
      - MAILER_SMTP_PASSWORD
      - MAILER_CMD_REGISTRATION
      - MAILER_CMD_FORGOT_PASSWORD
      - MAILER_CMD_CHANGE_EMAIL
      - PROJECT_TAG
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_MAIL_QUEUE

  api:
    build:
      target: production
    environment:
      - API_HOST
      - API_PORT
      - API_ACCESS_TOKEN_LIFETIME
      - API_ACCESS_TOKEN_SECRET_KEY
      - API_REFRESH_TOKEN_LIFETIME
      - API_REFRESH_TOKEN_SECRET_KEY
      - NGINX_HOST
      - PANEL_REACT_URL
      - PANEL_VUE_URL
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_MAIL_QUEUE
      - MAILER_CMD_REGISTRATION
      - MAILER_CMD_FORGOT_PASSWORD
      - MAILER_CMD_CHANGE_EMAIL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USER
      - REDIS_PASSWORD
      - REDIS_DB

  panel-react:
    build:
      target: production
      args:
        - PANEL_REACT_URL
        - API_HOST
        - API_PORT
        - API_URL
        - GOOGLE_CLIENT_ID

  panel-vue:
    build:
      target: production
      args:
        - PANEL_VUE_URL
        - API_HOST
        - API_PORT
        - API_URL
        - GOOGLE_CLIENT_ID
