version: "3.8"

services:

  nginx:
    build:
      target: production

  rabbitmq:
    build:
      target: production

  redis:
    build:
      target: production

  nest_core:
    build:
      target: production

  nest_mailer:
    build:
      target: production

  next:
    build:
      target: production