#!/bin/sh

run_check() {
  local label="$1"
  local command="$2"

  echo "$label"
  output=$($command 2>&1)
  status=$?
  if [ $status -ne 0 ]; then
    echo "❌ Command \"${command}\" failed"
    echo "$output"
    exit $status
  fi
}

# nest_core
run_check "🔍 Linting nest_core..." "npm --prefix nest_core run lint"
run_check "🧪 Running tests in nest_core..." "npm --prefix nest_core run test:e2e"

# nest_mailer
run_check "🔍 Linting nest_mailer..." "npm --prefix nest_mailer run lint"

# next
run_check "🔍 Linting next..." "npm --prefix next run lint:fix"
run_check "🧪 Running tests in next..." "npm --prefix next run test"

# nuxt
run_check "🔍 Linting nuxt..." "npm --prefix nuxt run lint:fix"
run_check "🧪 Running tests in nuxt..." "npm --prefix nuxt run test:ci"

# final
echo "✅ All checks passed!"