#!/bin/sh

# nest_core

echo "🔍 Linting nest_core..."
output=$(npm --prefix nest_core run lint 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Lint failed in nest_core"
  echo "$output"
  exit $status
fi

echo "🧪 Running tests in nest_core..."
output=$(npm --prefix nest_core run test:e2e 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Test failed in nest_core"
  echo "$output"
  exit $status
fi

# nest_mailer

echo "🔍 Linting nest_mailer..."
output=$(npm --prefix nest_mailer run lint 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Lint failed in nest_mailer"
  echo "$output"
  exit $status
fi

# next

echo "🔍 Linting next..."
output=$(npm --prefix next run lint:fix 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Lint failed in next"
  echo "$output"
  exit $status
fi

echo "🧪 Running tests in next..."
output=$(npm --prefix next run test 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Test failed in next"
  echo "$output"
  exit $status
fi

# nuxt

echo "🔍 Linting nuxt..."
output=$(npm --prefix nuxt run lint:fix 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Lint failed in nuxt"
  echo "$output"
  exit $status
fi

echo "🧪 Running tests in nuxt..."
output=$(npm --prefix nuxt run test:ci 2>&1)
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Test failed in nuxt"
  echo "$output"
  exit $status
fi

# final

echo "✅ All checks passed!"